import { FormulaDefinition } from '../types';

export const FORMULA_DATABASE: FormulaDefinition[] = [
  // ==========================================
  // --- MATHEMATICS: FRACTIONS & ALGEBRA ---
  // ==========================================
  {
    id: 'fractions-addition',
    subject: 'math',
    topic: 'Kasrlar (Arifmetika)',
    nameUzLatn: 'Kasrlarni qo‘shish va umumiy maxraj',
    nameUzCyrl: 'Касрларни қўшиш ва умумий махраж',
    nameRu: 'Сложение дробей и общий знаменатель',
    nameEn: 'Fraction Addition & Common Denominator',
    formulaLatex: '\\frac{a}{b} + \\frac{c}{d} = \\frac{a \\cdot d + b \\cdot c}{b \\cdot d}',
    plainFormula: 'a/b + c/d = (a*d + b*c)/(b*d)',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi kasr surati', nameUzCyrl: 'Биринчи каср сурати', nameRu: 'Числитель первой дроби', nameEn: 'First numerator', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'Birinchi kasr maxraji', nameUzCyrl: 'Биринчи каср махражи', nameRu: 'Знаменатель первой дроби', nameEn: 'First denominator', unit: '' },
      c: { symbol: 'c', nameUzLatn: 'Ikkinchi kasr surati', nameUzCyrl: 'Иккинчи каср сурати', nameRu: 'Числитель второй дроби', nameEn: 'Second numerator', unit: '' },
      d: { symbol: 'd', nameUzLatn: 'Ikkinchi kasr maxraji', nameUzCyrl: 'Иккинчи каср махражи', nameRu: 'Знаменатель второй дроби', nameEn: 'Second denominator', unit: '' },
    },
    rearrangements: [
      { target: 'EKUK', latex: 'b, d \\implies \\text{EKUK}(b, d)', explanationUzLatn: 'Maxrajlar uchun eng kichik umumiy karrali (EKUK) topiladi.' },
    ],
    sampleProblem: {
      textUzLatn: '3/4 va 5/6 kasrlarini qo‘shing.',
      textUzCyrl: '3/4 ва 5/6 касрларини қўшинг.',
      textRu: 'Сложите дроби 3/4 и 5/6.',
      textEn: 'Add fractions 3/4 and 5/6.',
      solutionInput: '3/4 + 5/6',
    },
    keywords: ['kasr', 'kasrlar', 'maxraj', 'surat', 'ekuk', 'fraction', 'denominator', 'дробь', 'сложение'],
  },

  {
    id: 'fractions-multiplication',
    subject: 'math',
    topic: 'Kasrlar (Arifmetika)',
    nameUzLatn: 'Kasrlarni ko‘paytirish va bo‘lish',
    nameUzCyrl: 'Касрларни кўпайтириш ва бўлиш',
    nameRu: 'Умножение и деление дробей',
    nameEn: 'Fraction Multiplication & Division',
    formulaLatex: '\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}, \\quad \\frac{a}{b} \\div \\frac{c}{d} = \\frac{a \\cdot d}{b \\cdot c}',
    plainFormula: '(a/b) * (c/d) = (a*c)/(b*d)',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi surat', nameUzCyrl: 'Биринчи сурат', nameRu: 'Числитель 1', nameEn: 'Numerator 1', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'Birinchi maxraj', nameUzCyrl: 'Биринчи махраж', nameRu: 'Знаменатель 1', nameEn: 'Denominator 1', unit: '' },
      c: { symbol: 'c', nameUzLatn: 'Ikkinchi surat', nameUzCyrl: 'Иккинчи сурат', nameRu: 'Числитель 2', nameEn: 'Numerator 2', unit: '' },
      d: { symbol: 'd', nameUzLatn: 'Ikkinchi maxraj', nameUzCyrl: 'Иккинчи махраж', nameRu: 'Знаменатель 2', nameEn: 'Denominator 2', unit: '' },
    },
    rearrangements: [
      { target: 'div', latex: '\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\times \\frac{d}{c}', explanationUzLatn: 'Kasrga bo‘lish ikkinchi kasrning teskarisiga ko‘paytirish demakdir.' },
    ],
    sampleProblem: {
      textUzLatn: '2/3 kasrni 4/5 kasrga ko‘paytiring.',
      textUzCyrl: '2/3 касрни 4/5 касрга кўпайтиринг.',
      textRu: 'Умножьте дробь 2/3 на дробь 4/5.',
      textEn: 'Multiply 2/3 by 4/5.',
      solutionInput: '2/3 * 4/5',
    },
    keywords: ['kasr ko‘paytirish', 'bo‘lish', 'fraction multiplication', 'multiply fractions', 'деление дробей'],
  },

  {
    id: 'difference-of-squares',
    subject: 'math',
    topic: 'Qisqa ko‘paytirish formulalari',
    nameUzLatn: 'Kvadratlar ayirmasi',
    nameUzCyrl: 'Квадратлар айирмаси',
    nameRu: 'Разность квадратов',
    nameEn: 'Difference of Squares',
    formulaLatex: 'a^2 - b^2 = (a - b)(a + b)',
    plainFormula: 'a^2 - b^2 = (a - b)*(a + b)',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi had', nameUzCyrl: 'Биринчи ҳад', nameRu: 'Первый член', nameEn: 'First term', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'Ikkinchi had', nameUzCyrl: 'Иккинчи ҳад', nameRu: 'Второй член', nameEn: 'Second term', unit: '' },
    },
    rearrangements: [
      { target: 'expand', latex: '(a-b)(a+b) = a^2 - b^2', explanationUzLatn: 'Qavslarni ochganda o‘rta hadlar qisqarib ketadi.' },
    ],
    sampleProblem: {
      textUzLatn: 'x² - 9 ifodani ko‘paytuvchilarga ajrating.',
      textUzCyrl: 'x² - 9 ифодани кўпайтувчиларга ажратинг.',
      textRu: 'Разложите на множители выражение x² - 9.',
      textEn: 'Factor the expression x² - 9.',
      solutionInput: 'x^2 - 9',
    },
    keywords: ['qisqa ko‘paytirish', 'kvadratlar ayirmasi', 'difference of squares', 'разность квадратов', 'formulalar'],
  },

  {
    id: 'square-of-binomial',
    subject: 'math',
    topic: 'Qisqa ko‘paytirish formulalari',
    nameUzLatn: 'Ikkihad yig‘indisi va ayirmasining kvadrati',
    nameUzCyrl: 'Иккиҳад йиғиндиси ва айирмасининг квадрати',
    nameRu: 'Квадрат суммы и разности',
    nameEn: 'Square of a Binomial',
    formulaLatex: '(a \\pm b)^2 = a^2 \\pm 2ab + b^2',
    plainFormula: '(a + b)^2 = a^2 + 2*a*b + b^2',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi had', nameUzCyrl: 'Биринчи ҳад', nameRu: 'Первый член', nameEn: 'First term', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'Ikkinchi had', nameUzCyrl: 'Иккинчи ҳад', nameRu: 'Второй член', nameEn: 'Second term', unit: '' },
    },
    rearrangements: [
      { target: 'plus', latex: '(a+b)^2 = a^2 + 2ab + b^2', explanationUzLatn: 'Yig‘indining kvadrati.' },
      { target: 'minus', latex: '(a-b)^2 = a^2 - 2ab + b^2', explanationUzLatn: 'Ayirmaning kvadrati.' },
    ],
    sampleProblem: {
      textUzLatn: '(x + 3)² ifodani qisqa ko‘paytirish formulasi orqali oching.',
      textUzCyrl: '(x + 3)² ифодани қисқа кўпайтириш формуласи орқали очинг.',
      textRu: 'Раскройте (x + 3)² по формуле квадрата суммы.',
      textEn: 'Expand (x + 3)² using the square of binomial.',
      solutionInput: '(x + 3)^2',
    },
    keywords: ['kvadrat', 'ikkihad', 'yig‘indi kvadrati', 'square of sum', 'квадрат суммы'],
  },

  {
    id: 'sum-diff-cubes',
    subject: 'math',
    topic: 'Qisqa ko‘paytirish formulalari',
    nameUzLatn: 'Kublar yig‘indisi va ayirmasi',
    nameUzCyrl: 'Кублар йиғиндиси ва айирмаси',
    nameRu: 'Сумма и разность кубов',
    nameEn: 'Sum and Difference of Cubes',
    formulaLatex: 'a^3 \\pm b^3 = (a \\pm b)(a^2 \\mp ab + b^2)',
    plainFormula: 'a^3 + b^3 = (a + b)*(a^2 - a*b + b^2)',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi had', nameUzCyrl: 'Биринчи ҳад', nameRu: 'Первый член', nameEn: 'First term', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'Ikkinchi had', nameUzCyrl: 'Иккинчи ҳад', nameRu: 'Второй член', nameEn: 'Second term', unit: '' },
    },
    rearrangements: [
      { target: 'diff', latex: 'a^3 - b^3 = (a - b)(a^2 + ab + b^2)', explanationUzLatn: 'Kublar ayirmasi formulasi.' },
    ],
    sampleProblem: {
      textUzLatn: 'x³ - 8 ifodani ko‘paytuvchilarga ajrating.',
      textUzCyrl: 'x³ - 8 ифодани кўпайтувчиларга ажратинг.',
      textRu: 'Разложите x³ - 8 на множители.',
      textEn: 'Factor x³ - 8.',
      solutionInput: 'x^3 - 8',
    },
    keywords: ['kublar', 'kublar ayirmasi', 'sum of cubes', 'difference of cubes', 'куб разности'],
  },

  {
    id: 'quadratic-equation',
    subject: 'math',
    topic: 'Tenglamalar (Algebra)',
    nameUzLatn: 'Kvadrat tenglama va diskriminant',
    nameUzCyrl: 'Квадрат тенглама ва дискриминант',
    nameRu: 'Квадратное уравнение и дискриминант',
    nameEn: 'Quadratic Equation & Discriminant',
    formulaLatex: 'a x^2 + b x + c = 0, \\quad D = b^2 - 4ac, \\quad x_{1,2} = \\frac{-b \\pm \\sqrt{D}}{2a}',
    plainFormula: 'x = (-b +- sqrt(b^2 - 4*a*c))/(2*a)',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Katta koeffitsiyent', nameUzCyrl: 'Катта коэффициент', nameRu: 'Старший коэф.', nameEn: 'Leading coeff.', unit: '' },
      b: { symbol: 'b', nameUzLatn: 'O‘rta koeffitsiyent', nameUzCyrl: 'Ўрта коэффициент', nameRu: 'Средний коэф.', nameEn: 'Middle coeff.', unit: '' },
      c: { symbol: 'c', nameUzLatn: 'Ozod had', nameUzCyrl: 'Озод ҳад', nameRu: 'Свободный член', nameEn: 'Constant term', unit: '' },
    },
    rearrangements: [
      { target: 'D', latex: 'D = b^2 - 4ac', explanationUzLatn: 'Diskriminant: agar D > 0 bo‘lsa 2 ta, D = 0 bo‘lsa 1 ta, D < 0 bo‘lsa haqiqiy ildiz yo‘q.' },
      { target: 'vieta', latex: 'x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 \\cdot x_2 = \\frac{c}{a}', explanationUzLatn: 'Viyet teoremasi.' },
    ],
    sampleProblem: {
      textUzLatn: 'x² - 5x + 6 = 0 tenglamaning ildizlarini toping.',
      textUzCyrl: 'x² - 5x + 6 = 0 тенгламанинг илдизларини топинг.',
      textRu: 'Найдите корни уравнения x² - 5x + 6 = 0.',
      textEn: 'Find the roots of x² - 5x + 6 = 0.',
      solutionInput: 'x^2 - 5x + 6 = 0',
    },
    keywords: ['kvadrat tenglama', 'diskriminant', 'ildizlar', 'quadratic equation', 'roots', 'дискриминант'],
  },

  {
    id: 'pythagorean-theorem',
    subject: 'math',
    topic: 'Geometriya (Uchburchak)',
    nameUzLatn: 'Pifagor teoremasi',
    nameUzCyrl: 'Пифагор теоремаси',
    nameRu: 'Теорема Пифагора',
    nameEn: 'Pythagorean Theorem',
    formulaLatex: 'a^2 + b^2 = c^2',
    plainFormula: 'a^2 + b^2 = c^2',
    variables: {
      a: { symbol: 'a', nameUzLatn: 'Birinchi katet', nameUzCyrl: 'Биринчи катет', nameRu: 'Первый катет', nameEn: 'First leg', unit: 'm' },
      b: { symbol: 'b', nameUzLatn: 'Ikkinchi katet', nameUzCyrl: 'Иккинчи катет', nameRu: 'Второй катет', nameEn: 'Second leg', unit: 'm' },
      c: { symbol: 'c', nameUzLatn: 'Gipotenuza', nameUzCyrl: 'Гипотенуза', nameRu: 'Гипотенуза', nameEn: 'Hypotenuse', unit: 'm' },
    },
    rearrangements: [
      { target: 'c', latex: 'c = \\sqrt{a^2 + b^2}', explanationUzLatn: 'Gipotenuzani topish.' },
      { target: 'a', latex: 'a = \\sqrt{c^2 - b^2}', explanationUzLatn: 'Katetni gipotenuza orqali topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'To‘g‘ri burchakli uchburchak katetlari a = 3 va b = 4 ga teng. Gipotenuzani toping.',
      textUzCyrl: 'Тўғри бурчакли учбурчак катетлари a = 3 ва b = 4 га тенг. Гипотенузани топинг.',
      textRu: 'Катеты прямоугольного треугольника равны 3 и 4. Найдите гипотенузу.',
      textEn: 'Legs of a right triangle are 3 and 4. Find the hypotenuse.',
      solutionInput: 'a = 3, b = 4, c = ?',
    },
    keywords: ['pifagor', 'pythagoras', 'gipotenuza', 'katet', 'uchburchak', 'гипотенуза'],
  },

  {
    id: 'triangle-heron',
    subject: 'math',
    topic: 'Geometriya (Yuzalar)',
    nameUzLatn: 'Geron formulasi (Uchburchak yuzi)',
    nameUzCyrl: 'Герон формуласи (Учбурчак юзи)',
    nameRu: 'Формула Герона',
    nameEn: "Heron's Formula",
    formulaLatex: 'S = \\sqrt{p(p-a)(p-b)(p-c)}, \\quad p = \\frac{a+b+c}{2}',
    plainFormula: 'S = sqrt(p*(p-a)*(p-b)*(p-c))',
    variables: {
      S: { symbol: 'S', nameUzLatn: 'Yuz', nameUzCyrl: 'Юз', nameRu: 'Площадь', nameEn: 'Area', unit: 'm²' },
      a: { symbol: 'a', nameUzLatn: '1-tomon', nameUzCyrl: '1-томон', nameRu: 'Сторона a', nameEn: 'Side a', unit: 'm' },
      b: { symbol: 'b', nameUzLatn: '2-tomon', nameUzCyrl: '2-томон', nameRu: 'Сторона b', nameEn: 'Side b', unit: 'm' },
      c: { symbol: 'c', nameUzLatn: '3-tomon', nameUzCyrl: '3-томон', nameRu: 'Сторона c', nameEn: 'Side c', unit: 'm' },
      p: { symbol: 'p', nameUzLatn: 'Yarim perimetr', nameUzCyrl: 'Ярим периметр', nameRu: 'Полупериметр', nameEn: 'Semiperimeter', unit: 'm' },
    },
    rearrangements: [
      { target: 'p', latex: 'p = \\frac{a + b + c}{2}', explanationUzLatn: 'Yarim perimetrni topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Tomonlari 5, 6, 7 bo‘lgan uchburchak yuzini toping.',
      textUzCyrl: 'Томонлари 5, 6, 7 бўлган учбурчак юзини топинг.',
      textRu: 'Найдите площадь треугольника со сторонами 5, 6, 7.',
      textEn: 'Find the area of a triangle with sides 5, 6, 7.',
      solutionInput: 'a = 5, b = 6, c = 7, S = ?',
    },
    keywords: ['geron', 'heron', 'uchburchak yuzi', 'triangle area', 'формула герона'],
  },

  {
    id: 'circle-area-circumference',
    subject: 'math',
    topic: 'Geometriya (Aylana va Doira)',
    nameUzLatn: 'Doira yuzi va aylana uzunligi',
    nameUzCyrl: 'Доира юзи ва айлана узунлиги',
    nameRu: 'Площадь круга и длина окружности',
    nameEn: 'Circle Area & Circumference',
    formulaLatex: 'S = \\pi r^2, \\quad C = 2 \\pi r',
    plainFormula: 'S = pi * r^2, C = 2 * pi * r',
    variables: {
      S: { symbol: 'S', nameUzLatn: 'Doira yuzi', nameUzCyrl: 'Доира юзи', nameRu: 'Площадь', nameEn: 'Area', unit: 'm²' },
      C: { symbol: 'C', nameUzLatn: 'Aylana uzunligi', nameUzCyrl: 'Айлана узунлиги', nameRu: 'Длина', nameEn: 'Circumference', unit: 'm' },
      r: { symbol: 'r', nameUzLatn: 'Radius', nameUzCyrl: 'Радиус', nameRu: 'Радиус', nameEn: 'Radius', unit: 'm' },
    },
    rearrangements: [
      { target: 'r', latex: 'r = \\sqrt{\\frac{S}{\\pi}}', explanationUzLatn: 'Radiusni yuz orqali topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Radiusi 7 m bo‘lgan doiraning yuzini toping.',
      textUzCyrl: 'Радиуси 7 м бўлган доиранинг юзини топинг.',
      textRu: 'Найдите площадь круга радиусом 7 м.',
      textEn: 'Find area of circle with radius 7 m.',
      solutionInput: 'r = 7, S = ?',
    },
    keywords: ['aylana', 'doira', 'circle', 'radius', 'pi', 'площадь круга'],
  },

  {
    id: 'trig-identity',
    subject: 'math',
    topic: 'Trigonometriya',
    nameUzLatn: 'Asosiy trigonometrik ayniyat',
    nameUzCyrl: 'Асосий тригонометрик айният',
    nameRu: 'Основное тригонометрическое тождество',
    nameEn: 'Fundamental Trigonometric Identity',
    formulaLatex: '\\sin^2(\\alpha) + \\cos^2(\\alpha) = 1',
    plainFormula: 'sin(x)^2 + cos(x)^2 = 1',
    variables: {
      alpha: { symbol: '\\alpha', nameUzLatn: 'Burchak', nameUzCyrl: 'Бурчак', nameRu: 'Угол', nameEn: 'Angle', unit: '°' },
    },
    rearrangements: [
      { target: 'sin', latex: '\\sin(\\alpha) = \\pm \\sqrt{1 - \\cos^2(\\alpha)}', explanationUzLatn: 'Sinusni kosinus orqali topish.' },
      { target: 'cos', latex: '\\cos(\\alpha) = \\pm \\sqrt{1 - \\sin^2(\\alpha)}', explanationUzLatn: 'Kosinusni sinus orqali topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Agar sin(a) = 0.6 bo‘lsa, cos(a) ni toping.',
      textUzCyrl: 'Агар sin(a) = 0.6 бўлса, cos(a) ни топинг.',
      textRu: 'Если sin(a) = 0.6, найдите cos(a).',
      textEn: 'If sin(a) = 0.6, find cos(a).',
      solutionInput: 'sin(a) = 0.6, cos(a) = ?',
    },
    keywords: ['trigonometriya', 'sinus', 'kosinus', 'trigonometry', 'тригонометрия'],
  },

  {
    id: 'derivative-power-rule',
    subject: 'math',
    topic: 'Matematik Analiz (Hosilalar)',
    nameUzLatn: 'Darajali funksiyaning hosilasi',
    nameUzCyrl: 'Даражали функциянинг ҳосиласи',
    nameRu: 'Производная степенной функции',
    nameEn: 'Power Rule for Derivatives',
    formulaLatex: '(x^n)\' = n \\cdot x^{n-1}',
    plainFormula: 'd/dx(x^n) = n * x^(n-1)',
    variables: {
      x: { symbol: 'x', nameUzLatn: 'O‘zgaruvchi', nameUzCyrl: 'Ўзгарувчи', nameRu: 'Переменная', nameEn: 'Variable', unit: '' },
      n: { symbol: 'n', nameUzLatn: 'Daraja ko‘rsatkichi', nameUzCyrl: 'Даража кўрсаткичи', nameRu: 'Показатель', nameEn: 'Exponent', unit: '' },
    },
    rearrangements: [],
    sampleProblem: {
      textUzLatn: 'f(x) = x⁴ funksiyaning hosilasini toping.',
      textUzCyrl: 'f(x) = x⁴ функциянинг ҳосиласини топинг.',
      textRu: 'Найдите производную функции f(x) = x⁴.',
      textEn: 'Find derivative of f(x) = x⁴.',
      solutionInput: 'd/dx(x^4)',
    },
    keywords: ['hosila', 'analiz', 'derivative', 'power rule', 'производная'],
  },

  // ==========================================
  // --- PHYSICS: MECHANICS & KINEMATICS ---
  // ==========================================
  {
    id: 'newton-second-law',
    subject: 'physics',
    topic: 'Mexanika (Dinamika)',
    nameUzLatn: 'Nyutonning ikkinchi qonuni',
    nameUzCyrl: 'Ньютоннинг иккинчи қонуни',
    nameRu: 'Второй закон Ньютона',
    nameEn: "Newton's Second Law",
    formulaLatex: 'F = m \\cdot a',
    plainFormula: 'F = m * a',
    variables: {
      F: { symbol: 'F', nameUzLatn: 'Kuch', nameUzCyrl: 'Куч', nameRu: 'Сила', nameEn: 'Force', unit: 'N' },
      m: { symbol: 'm', nameUzLatn: 'Massa', nameUzCyrl: 'Масса', nameRu: 'Масса', nameEn: 'Mass', unit: 'kg' },
      a: { symbol: 'a', nameUzLatn: 'Tezlanish', nameUzCyrl: 'Тезланиш', nameRu: 'Ускорение', nameEn: 'Acceleration', unit: 'm/s²' },
    },
    rearrangements: [
      { target: 'a', latex: 'a = \\frac{F}{m}', explanationUzLatn: 'Tezlanishni topish uchun kuchni massaga bo‘lamiz.' },
      { target: 'm', latex: 'm = \\frac{F}{a}', explanationUzLatn: 'Massani topish uchun kuchni tezlanishga bo‘lamiz.' },
    ],
    sampleProblem: {
      textUzLatn: '5 kg massali jismga 20 N kuch ta‘sir etmoqda. Tezlanishni toping.',
      textUzCyrl: '5 кг массали жисмга 20 Н куч таъсир этмоқда. Тезланишни топинг.',
      textRu: 'На тело массой 5 кг действует сила 20 Н. Найдите ускорение.',
      textEn: 'A force of 20 N acts on a 5 kg mass. Find the acceleration.',
      solutionInput: 'm = 5 kg, F = 20 N, a = ?',
    },
    keywords: ['nyuton', 'newton', 'kuch', 'massa', 'tezlanish', 'force', 'mass', 'acceleration', 'f=ma', 'динамика'],
  },

  {
    id: 'speed-distance-time',
    subject: 'physics',
    topic: 'Mexanika (Kinematika)',
    nameUzLatn: 'To‘g‘ri chiziqli tekis harakat tezligi',
    nameUzCyrl: 'Тўғри чизиқли текис ҳаракат тезлиги',
    nameRu: 'Скорость равномерного движения',
    nameEn: 'Uniform Speed Formula',
    formulaLatex: 'v = \\frac{s}{t}',
    plainFormula: 'v = s / t',
    variables: {
      v: { symbol: 'v', nameUzLatn: 'Tezlik', nameUzCyrl: 'Тезлик', nameRu: 'Скорость', nameEn: 'Speed', unit: 'm/s' },
      s: { symbol: 's', nameUzLatn: 'Masofa', nameUzCyrl: 'Масофа', nameRu: 'Путь', nameEn: 'Distance', unit: 'm' },
      t: { symbol: 't', nameUzLatn: 'Vaqt', nameUzCyrl: 'Вақт', nameRu: 'Время', nameEn: 'Time', unit: 's' },
    },
    rearrangements: [
      { target: 's', latex: 's = v \\cdot t', explanationUzLatn: 'Masofani topish uchun tezlikni vaqtga ko‘paytiramiz.' },
      { target: 't', latex: 't = \\frac{s}{v}', explanationUzLatn: 'Vaqtni topish uchun masofani tezlikka bo‘lamiz.' },
    ],
    sampleProblem: {
      textUzLatn: 'Avtomobil 72 km/h tezlik bilan 30 sekund harakatlandi. Yo‘l masofasini toping.',
      textUzCyrl: 'Автомобиль 72 км/ч тезлик билан 30 секунд ҳаракатланди. Йўл масофасини топинг.',
      textRu: 'Автомобиль двигался со скоростью 72 км/ч в течение 30 с. Найдите путь.',
      textEn: 'A car travels at 72 km/h for 30 seconds. Find the distance.',
      solutionInput: 'v = 72 km/h, t = 30 s, s = ?',
    },
    keywords: ['tezlik', 'masofa', 'vaqt', 'speed', 'distance', 'time', 'v=s/t', 'скорость'],
  },

  {
    id: 'accelerated-motion-distance',
    subject: 'physics',
    topic: 'Mexanika (Kinematika)',
    nameUzLatn: 'Tekis tezlanuvchan harakatda yo‘l',
    nameUzCyrl: 'Текис тезланувчан ҳаракатда йўл',
    nameRu: 'Путь при равноускоренном движении',
    nameEn: 'Distance in Accelerated Motion',
    formulaLatex: 's = v_0 t + \\frac{a t^2}{2}, \\quad v^2 - v_0^2 = 2 a s',
    plainFormula: 's = v0 * t + 0.5 * a * t^2',
    variables: {
      s: { symbol: 's', nameUzLatn: 'Masofa', nameUzCyrl: 'Масофа', nameRu: 'Путь', nameEn: 'Distance', unit: 'm' },
      v0: { symbol: 'v_0', nameUzLatn: 'Boshlang‘ich tezlik', nameUzCyrl: 'Бошланғич тезлик', nameRu: 'Нач. скорость', nameEn: 'Initial velocity', unit: 'm/s' },
      a: { symbol: 'a', nameUzLatn: 'Tezlanish', nameUzCyrl: 'Тезланиш', nameRu: 'Ускорение', nameEn: 'Acceleration', unit: 'm/s²' },
      t: { symbol: 't', nameUzLatn: 'Vaqt', nameUzCyrl: 'Вақт', nameRu: 'Время', nameEn: 'Time', unit: 's' },
    },
    rearrangements: [
      { target: 'a', latex: 'a = \\frac{2(s - v_0 t)}{t^2}', explanationUzLatn: 'Tezlanishni topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Tinch turgan jism 2 m/s² tezlanish bilan 4 sekund harakatlandi. Bosib o‘tilgan yo‘lni toping.',
      textUzCyrl: 'Тинч турган жисм 2 м/с² тезланиш билан 4 секунд ҳаракатланди. Босиб ўтилган йўлни топинг.',
      textRu: 'Тело начало движение из состояния покоя с ускорением 2 м/с² за 4 с. Найдите путь.',
      textEn: 'A body starts from rest with 2 m/s² acceleration for 4 s. Find distance.',
      solutionInput: 'v0 = 0 m/s, a = 2 m/s^2, t = 4 s, s = ?',
    },
    keywords: ['tezlanuvchan harakat', 'kinematika', 'accelerated motion', 'ускоренное движение'],
  },

  {
    id: 'kinetic-potential-energy',
    subject: 'physics',
    topic: 'Mexanika (Energiya)',
    nameUzLatn: 'Kinetik va potensial energiya',
    nameUzCyrl: 'Кинетик ва потенциал энергия',
    nameRu: 'Кинетическая и потенциальная энергия',
    nameEn: 'Kinetic and Potential Energy',
    formulaLatex: 'E_k = \\frac{m v^2}{2}, \\quad E_p = m g h',
    plainFormula: 'Ek = 0.5 * m * v^2, Ep = m * g * h',
    variables: {
      Ek: { symbol: 'E_k', nameUzLatn: 'Kinetik energiya', nameUzCyrl: 'Кинетик энергия', nameRu: 'Кин. энергия', nameEn: 'Kinetic energy', unit: 'J' },
      Ep: { symbol: 'E_p', nameUzLatn: 'Potensial energiya', nameUzCyrl: 'Потенциал энергия', nameRu: 'Пот. энергия', nameEn: 'Potential energy', unit: 'J' },
      m: { symbol: 'm', nameUzLatn: 'Massa', nameUzCyrl: 'Масса', nameRu: 'Масса', nameEn: 'Mass', unit: 'kg' },
      v: { symbol: 'v', nameUzLatn: 'Tezlik', nameUzCyrl: 'Тезлик', nameRu: 'Скорость', nameEn: 'Velocity', unit: 'm/s' },
      h: { symbol: 'h', nameUzLatn: 'Balandlik', nameUzCyrl: 'Баландлик', nameRu: 'Высота', nameEn: 'Height', unit: 'm' },
    },
    rearrangements: [
      { target: 'v', latex: 'v = \\sqrt{\\frac{2 E_k}{m}}', explanationUzLatn: 'Tezlikni kinetik energiya orqali topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Massasi 2 kg bo‘lgan jism 10 m/s tezlikda harakatlanmoqda. Uning kinetik energiyasini toping.',
      textUzCyrl: 'Массаси 2 кг бўлган жисм 10 м/с тезликда ҳаракатланмоқда. Унинг кинетик энергиясини топинг.',
      textRu: 'Тело массой 2 кг движется со скоростью 10 м/с. Найдите кинетическую энергию.',
      textEn: 'A 2 kg mass moves at 10 m/s. Find its kinetic energy.',
      solutionInput: 'm = 2 kg, v = 10 m/s, Ek = ?',
    },
    keywords: ['energiya', 'kinetik', 'potensial', 'energy', 'joule', 'энергия'],
  },

  {
    id: 'work-and-power',
    subject: 'physics',
    topic: 'Mexanika (Ish va Quvvat)',
    nameUzLatn: 'Mexanik ish va quvvat',
    nameUzCyrl: 'Механик иш ва қувват',
    nameRu: 'Механическая работа и мощность',
    nameEn: 'Mechanical Work and Power',
    formulaLatex: 'A = F \\cdot s \\cdot \\cos(\\alpha), \\quad N = \\frac{A}{t}',
    plainFormula: 'A = F * s, N = A / t',
    variables: {
      A: { symbol: 'A', nameUzLatn: 'Mexanik ish', nameUzCyrl: 'Механик иш', nameRu: 'Работа', nameEn: 'Work', unit: 'J' },
      N: { symbol: 'N', nameUzLatn: 'Quvvat', nameUzCyrl: 'Қувват', nameRu: 'Мощность', nameEn: 'Power', unit: 'W' },
      F: { symbol: 'F', nameUzLatn: 'Kuch', nameUzCyrl: 'Куч', nameRu: 'Сила', nameEn: 'Force', unit: 'N' },
      s: { symbol: 's', nameUzLatn: 'Masofa', nameUzCyrl: 'Масофа', nameRu: 'Перемещение', nameEn: 'Displacement', unit: 'm' },
      t: { symbol: 't', nameUzLatn: 'Vaqt', nameUzCyrl: 'Вақт', nameRu: 'Время', nameEn: 'Time', unit: 's' },
    },
    rearrangements: [
      { target: 'F', latex: 'F = \\frac{A}{s}', explanationUzLatn: 'Kuchni ish orqali topish.' },
      { target: 't', latex: 't = \\frac{A}{N}', explanationUzLatn: 'Ish bajarilish vaqtini topish.' },
    ],
    sampleProblem: {
      textUzLatn: '50 N kuch jismni 10 metrga ko‘chirdi. Bajarilgan ishni hisoblang.',
      textUzCyrl: '50 Н куч жисмни 10 метрга кўчирди. Бажарилган ишни ҳисобланг.',
      textRu: 'Сила 50 Н переместила тело на 10 м. Найдите работу.',
      textEn: 'A force of 50 N moved an object 10 m. Calculate the work.',
      solutionInput: 'F = 50 N, s = 10 m, A = ?',
    },
    keywords: ['ish', 'quvvat', 'work', 'power', 'vatt', 'djoule', 'работа', 'мощность'],
  },

  // ==========================================
  // --- PHYSICS: THERMODYNAMICS ---
  // ==========================================
  {
    id: 'heat-capacity',
    subject: 'physics',
    topic: 'Molekulyar fizika va Termodinamika',
    nameUzLatn: 'Issiqlik miqdori formulasi',
    nameUzCyrl: 'Иссиқлик миқдори формуласи',
    nameRu: 'Количество теплоты при нагревании',
    nameEn: 'Heat Transfer Formula',
    formulaLatex: 'Q = c \\cdot m \\cdot \\Delta t',
    plainFormula: 'Q = c * m * deltaT',
    variables: {
      Q: { symbol: 'Q', nameUzLatn: 'Issiqlik miqdori', nameUzCyrl: 'Иссиқлик миқдори', nameRu: 'Теплота', nameEn: 'Heat energy', unit: 'J' },
      c: { symbol: 'c', nameUzLatn: 'Solishtirma issiqlik sig‘imi', nameUzCyrl: 'Солиштирма иссиқлик сиғими', nameRu: 'Удельная теплоемкость', nameEn: 'Specific heat', unit: 'J/(kg·°C)' },
      m: { symbol: 'm', nameUzLatn: 'Massa', nameUzCyrl: 'Масса', nameRu: 'Масса', nameEn: 'Mass', unit: 'kg' },
      deltaT: { symbol: '\\Delta t', nameUzLatn: 'Harorat o‘zgarishi', nameUzCyrl: 'Ҳарорат ўзгариши', nameRu: 'Изм. температуры', nameEn: 'Temp. change', unit: '°C' },
    },
    rearrangements: [
      { target: 'deltaT', latex: '\\Delta t = \\frac{Q}{c \\cdot m}', explanationUzLatn: 'Harorat o‘zgarishini topish.' },
      { target: 'm', latex: 'm = \\frac{Q}{c \\cdot \\Delta t}', explanationUzLatn: 'Massani topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Massasi 2 kg bo‘lgan suvni 20°C dan 50°C gacha isitish uchun qancha issiqlik kerak? (c = 4200 J/(kg·°C))',
      textUzCyrl: 'Массаси 2 кг бўлган сувни 20°C дан 50°C гача иситиш учун қанча иссиқлик керак?',
      textRu: 'Какое количество теплоты требуется для нагрева 2 кг воды от 20°C до 50°C?',
      textEn: 'How much heat is needed to heat 2 kg of water from 20°C to 50°C?',
      solutionInput: 'm = 2 kg, c = 4200 J/(kg*C), deltaT = 30 C, Q = ?',
    },
    keywords: ['issiqlik', 'termodinamika', 'temperatura', 'heat', 'q=cmdt', 'теплоемкость'],
  },

  {
    id: 'ideal-gas-law',
    subject: 'physics',
    topic: 'Molekulyar fizika va Termodinamika',
    nameUzLatn: 'Mendeleyev-Klapeyron tenglamasi',
    nameUzCyrl: 'Менделеев-Клапейрон тенгламаси',
    nameRu: 'Уравнение Менделеева-Клапейрона',
    nameEn: 'Ideal Gas Law',
    formulaLatex: 'p \\cdot V = \\nu \\cdot R \\cdot T, \\quad \\nu = \\frac{m}{M}',
    plainFormula: 'p * V = (m/M) * R * T',
    variables: {
      p: { symbol: 'p', nameUzLatn: 'Bosim', nameUzCyrl: 'Босим', nameRu: 'Давление', nameEn: 'Pressure', unit: 'Pa' },
      V: { symbol: 'V', nameUzLatn: 'Hajm', nameUzCyrl: 'Ҳажм', nameRu: 'Объем', nameEn: 'Volume', unit: 'm³' },
      T: { symbol: 'T', nameUzLatn: 'Absolyut harorat', nameUzCyrl: 'Абсолют ҳарорат', nameRu: 'Температура', nameEn: 'Temperature', unit: 'K' },
      R: { symbol: 'R', nameUzLatn: 'Universal gaz doimiysi (8.31 J/(mol·K))', nameUzCyrl: 'Газ доимийси', nameRu: 'Газовая постоянная', nameEn: 'Gas constant', unit: 'J/(mol·K)' },
    },
    rearrangements: [
      { target: 'p', latex: 'p = \\frac{\\nu R T}{V}', explanationUzLatn: 'Gaz bosimini topish.' },
    ],
    sampleProblem: {
      textUzLatn: '1 mol ideal gaz 300 K haroratda 0.025 m³ hajmda qanday bosim hosil qiladi?',
      textUzCyrl: '1 моль идеал газ 300 К ҳароратда 0.025 м³ ҳажмда қандай босим ҳосил қилади?',
      textRu: 'Какое давление оказывает 1 моль идеального газа при 300 К в объеме 0.025 м³?',
      textEn: 'What pressure does 1 mol of ideal gas exert at 300 K in 0.025 m³?',
      solutionInput: 'nu = 1 mol, T = 300 K, V = 0.025 m^3, R = 8.31, p = ?',
    },
    keywords: ['gaz qonuni', 'mendeleyev', 'ideal gas', 'bosim', 'hajm', 'менделеев-клапейрон'],
  },

  // ==========================================
  // --- PHYSICS: ELECTRICITY & MAGNETISM ---
  // ==========================================
  {
    id: 'ohm-law',
    subject: 'physics',
    topic: 'Elektr va Magnetizm',
    nameUzLatn: 'Zanjir qismi uchun Om qonuni',
    nameUzCyrl: 'Занжир қисми учун Ом қонуни',
    nameRu: 'Закон Ома для участка цепи',
    nameEn: "Ohm's Law",
    formulaLatex: 'I = \\frac{U}{R}',
    plainFormula: 'I = U / R',
    variables: {
      I: { symbol: 'I', nameUzLatn: 'Tok kuchi', nameUzCyrl: 'Ток кучи', nameRu: 'Сила тока', nameEn: 'Current', unit: 'A' },
      U: { symbol: 'U', nameUzLatn: 'Kuchlanish', nameUzCyrl: 'Кучланиш', nameRu: 'Напряжение', nameEn: 'Voltage', unit: 'V' },
      R: { symbol: 'R', nameUzLatn: 'Qarshilik', nameUzCyrl: 'Қаршилик', nameRu: 'Сопротивление', nameEn: 'Resistance', unit: 'Ω' },
    },
    rearrangements: [
      { target: 'U', latex: 'U = I \\cdot R', explanationUzLatn: 'Kuchlanishni topish uchun tok kuchini qarshilikka ko‘paytiramiz.' },
      { target: 'R', latex: 'R = \\frac{U}{I}', explanationUzLatn: 'Qarshilikni topish uchun kuchlanishni tok kuchiga bo‘lamiz.' },
    ],
    sampleProblem: {
      textUzLatn: '12 V kuchlanish ostidagi o‘tkazgichdan 4 Ω qarshilik o‘tganda tok kuchi qancha bo‘ladi?',
      textUzCyrl: '12 В кучланиш остидаги ўтказгичдан 4 Ом қаршилик ўтганда ток кучи қанча бўлади?',
      textRu: 'Какова сила тока в проводнике сопротивлением 4 Ом под напряжением 12 В?',
      textEn: 'Find the current through a 4 Ω resistor connected to a 12 V source.',
      solutionInput: 'U = 12 V, R = 4 ohm, I = ?',
    },
    keywords: ['om qonuni', 'ohm', 'tok kuchi', 'kuchlanish', 'qarshilik', 'voltage', 'current', 'закон ома'],
  },

  {
    id: 'coulomb-law',
    subject: 'physics',
    topic: 'Elektr va Magnetizm',
    nameUzLatn: 'Kulon qonuni',
    nameUzCyrl: 'Кулон қонуни',
    nameRu: 'Закон Кулона',
    nameEn: "Coulomb's Law",
    formulaLatex: 'F = k \\cdot \\frac{|q_1 \\cdot q_2|}{r^2}, \\quad k = 9 \\cdot 10^9 \\text{ N}\\cdot\\text{m}^2/\\text{C}^2',
    plainFormula: 'F = k * abs(q1 * q2) / r^2',
    variables: {
      F: { symbol: 'F', nameUzLatn: 'O‘zaro ta‘sir kuchi', nameUzCyrl: 'Ўзаро таъсир кучи', nameRu: 'Сила', nameEn: 'Force', unit: 'N' },
      q1: { symbol: 'q_1', nameUzLatn: 'Birinchi zaryad', nameUzCyrl: 'Биринчи заряд', nameRu: 'Заряд 1', nameEn: 'Charge 1', unit: 'C' },
      q2: { symbol: 'q_2', nameUzLatn: 'Ikkinchi zaryad', nameUzCyrl: 'Иккинчи заряд', nameRu: 'Заряд 2', nameEn: 'Charge 2', unit: 'C' },
      r: { symbol: 'r', nameUzLatn: 'Orasidagi masofa', nameUzCyrl: 'Орасидаги масофа', nameRu: 'Расстояние', nameEn: 'Distance', unit: 'm' },
    },
    rearrangements: [
      { target: 'r', latex: 'r = \\sqrt{k \\frac{|q_1 q_2|}{F}}', explanationUzLatn: 'Zaryadlar orasidagi masofani topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'q₁ = 2·10⁻⁶ C va q₂ = 3·10⁻⁶ C zaryadlar 0.3 m masofada qanday kuch bilan ta‘sirlashadi?',
      textUzCyrl: 'q₁ = 2·10⁻⁶ C ва q₂ = 3·10⁻⁶ C зарядлар 0.3 м масофада қандай куч билан таъсирлашади?',
      textRu: 'С какой силой взаимодействуют заряды q₁ = 2 мкКл и q₂ = 3 мкКл на расстоянии 0.3 м?',
      textEn: 'What force acts between q₁ = 2 µC and q₂ = 3 µC at 0.3 m distance?',
      solutionInput: 'q1 = 2e-6 C, q2 = 3e-6 C, r = 0.3 m, F = ?',
    },
    keywords: ['kulon', 'coulomb', 'zaryad', 'charge', 'elektr', 'закон кулона'],
  },

  {
    id: 'joule-lenz-law',
    subject: 'physics',
    topic: 'Elektr va Magnetizm',
    nameUzLatn: 'Joul-Lens qonuni va elektr quvvati',
    nameUzCyrl: 'Жоуль-Ленц қонуни ва электр қуввати',
    nameRu: 'Закон Джоуля-Ленца',
    nameEn: 'Joule-Lenz Law & Electric Power',
    formulaLatex: 'Q = I^2 \\cdot R \\cdot t = U \\cdot I \\cdot t, \\quad P = U \\cdot I = I^2 \\cdot R',
    plainFormula: 'Q = I^2 * R * t, P = U * I',
    variables: {
      Q: { symbol: 'Q', nameUzLatn: 'Ajralgan issiqlik', nameUzCyrl: 'Ажралган иссиқлик', nameRu: 'Теплота', nameEn: 'Heat', unit: 'J' },
      P: { symbol: 'P', nameUzLatn: 'Elektr quvvati', nameUzCyrl: 'Электр қуввати', nameRu: 'Мощность', nameEn: 'Power', unit: 'W' },
      I: { symbol: 'I', nameUzLatn: 'Tok kuchi', nameUzCyrl: 'Ток кучи', nameRu: 'Сила тока', nameEn: 'Current', unit: 'A' },
      R: { symbol: 'R', nameUzLatn: 'Qarshilik', nameUzCyrl: 'Қаршилик', nameRu: 'Сопротивление', nameEn: 'Resistance', unit: 'Ω' },
      t: { symbol: 't', nameUzLatn: 'Vaqt', nameUzCyrl: 'Вақт', nameRu: 'Время', nameEn: 'Time', unit: 's' },
    },
    rearrangements: [
      { target: 'R', latex: 'R = \\frac{Q}{I^2 t}', explanationUzLatn: 'Qarshilikni topish.' },
    ],
    sampleProblem: {
      textUzLatn: '2 A tok 5 Ω qarshilikli o‘tkazgichdan 10 sekund oqib o‘tganda qancha issiqlik ajraladi?',
      textUzCyrl: '2 А ток 5 Ом қаршиликли ўтказгичдан 10 секунд оқиб ўтганда қанча иссиқлик ажралади?',
      textRu: 'Какое количество теплоты выделится в проводнике 5 Ом при токе 2 А за 10 с?',
      textEn: 'How much heat is produced by 2 A current through 5 Ω in 10 s?',
      solutionInput: 'I = 2 A, R = 5 ohm, t = 10 s, Q = ?',
    },
    keywords: ['joul-lens', 'joule', 'elektr issiqligi', 'quvvat', 'джоуль-ленц'],
  },

  // ==========================================
  // --- PHYSICS: OPTICS ---
  // ==========================================
  {
    id: 'snell-law',
    subject: 'physics',
    topic: 'Optika (Yorug‘lik qonunlari)',
    nameUzLatn: 'Yorug‘likning sinish qonuni (Snellius qonuni)',
    nameUzCyrl: 'Ёруғликнинг синиш қонуни (Снеллиус қонуни)',
    nameRu: 'Закон преломления света (Снеллиуса)',
    nameEn: "Snell's Law of Refraction",
    formulaLatex: '\\frac{\\sin(\\alpha)}{\\sin(\\beta)} = \\frac{n_2}{n_1} = n_{21}',
    plainFormula: 'sin(alpha) / sin(beta) = n',
    variables: {
      alpha: { symbol: '\\alpha', nameUzLatn: 'Tushish burchagi', nameUzCyrl: 'Тушиш бурчаги', nameRu: 'Угол падения', nameEn: 'Angle of incidence', unit: '°' },
      beta: { symbol: '\\beta', nameUzLatn: 'Sinish burchagi', nameUzCyrl: 'Синиш бурчаги', nameRu: 'Угол преломления', nameEn: 'Angle of refraction', unit: '°' },
      n: { symbol: 'n', nameUzLatn: 'Nisbiy sinish ko‘rsatkichi', nameUzCyrl: 'Нисбий синиш кўрсаткичи', nameRu: 'Показатель преломления', nameEn: 'Refractive index', unit: '' },
    },
    rearrangements: [
      { target: 'sin_beta', latex: '\\sin(\\beta) = \\frac{\\sin(\\alpha)}{n}', explanationUzLatn: 'Sinish burchagini topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Yorug‘lik nurining tushish burchagi 30°, sinish ko‘rsatkichi n = 1.5 bo‘lsa, sinish burchagini toping.',
      textUzCyrl: 'Ёруғлик нурининг тушиш бурчаги 30°, синиш кўрсаткичи n = 1.5 бўлса, синиш бурчагини топинг.',
      textRu: 'Угол падения 30°, показатель преломления n = 1.5. Найдите угол преломления.',
      textEn: 'Incident angle is 30°, index n = 1.5. Find refraction angle.',
      solutionInput: 'alpha = 30 deg, n = 1.5, beta = ?',
    },
    keywords: ['optika', 'sinish', 'snell', 'optics', 'yoruglik', 'преломление света'],
  },

  {
    id: 'thin-lens-equation',
    subject: 'physics',
    topic: 'Optika (Linzalar)',
    nameUzLatn: 'Yupqa linza formulasi',
    nameUzCyrl: 'Юпқа линза формуласи',
    nameRu: 'Формула тонкой линзы',
    nameEn: 'Thin Lens Formula',
    formulaLatex: '\\frac{1}{F} = \\frac{1}{d} + \\frac{1}{f}, \\quad D = \\frac{1}{F}',
    plainFormula: '1/F = 1/d + 1/f',
    variables: {
      F: { symbol: 'F', nameUzLatn: 'Fokus masofasi', nameUzCyrl: 'Фокус масофаси', nameRu: 'Фокусное расстояние', nameEn: 'Focal length', unit: 'm' },
      d: { symbol: 'd', nameUzLatn: 'Buyumdan linzagacha masofa', nameUzCyrl: 'Буюмдан линзагача масофа', nameRu: 'Расстояние до предмета', nameEn: 'Object distance', unit: 'm' },
      f: { symbol: 'f', nameUzLatn: 'Tasvirdan linzagacha masofa', nameUzCyrl: 'Тасвирдан линзагача масофа', nameRu: 'Расстояние до изображения', nameEn: 'Image distance', unit: 'm' },
      D: { symbol: 'D', nameUzLatn: 'Optik kuch', nameUzCyrl: 'Оптик куч', nameRu: 'Оптическая сила', nameEn: 'Optical power', unit: 'dptr' },
    },
    rearrangements: [
      { target: 'f', latex: 'f = \\frac{F \\cdot d}{d - F}', explanationUzLatn: 'Tasvir masofasini topish.' },
    ],
    sampleProblem: {
      textUzLatn: 'Fokus masofasi 0.2 m bo‘lgan linzadan 0.3 m masofada buyum turibdi. Tasvir masofasini toping.',
      textUzCyrl: 'Фокус масофаси 0.2 м бўлган линзадан 0.3 м масофада буюм турибди. Тасвир масофасини топинг.',
      textRu: 'Предмет находится на расстоянии 0.3 м от линзы с F = 0.2 м. Найдите расстояние до изображения.',
      textEn: 'An object is 0.3 m from a lens with F = 0.2 m. Find image distance.',
      solutionInput: 'F = 0.2 m, d = 0.3 m, f = ?',
    },
    keywords: ['linza', 'fokus', 'yupqa linza', 'lens', 'dioptriya', 'тонкая линза'],
  },
];
