import { QuizQuestion } from '../types';

export const QUIZ_DATABASE: QuizQuestion[] = [
  // --- KASRLAR (FRACTIONS) ---
  {
    id: 'quiz-frac-1',
    category: 'fraction',
    level: 'school',
    questionUzLatn: '3/4 + 5/6 kasrlarini qo‘shganda natija nima bo‘ladi?',
    questionUzCyrl: '3/4 + 5/6 касрларини қўшганда натижа нима бўлади?',
    questionRu: 'Чему равна сумма дробей 3/4 + 5/6?',
    questionEn: 'What is 3/4 + 5/6?',
    problemInput: '3/4 + 5/6',
    options: [
      { id: 'opt-1', text: '19/12 (yoki 1 7/12)', isCorrect: true },
      { id: 'opt-2', text: '8/10 (4/5)', isCorrect: false },
      { id: 'opt-3', text: '15/24', isCorrect: false },
      { id: 'opt-4', text: '23/12', isCorrect: false },
    ],
    explanationUzLatn: 'Maxrajlar 4 va 6 uchun EKUK = 12. 3/4 = 9/12 va 5/6 = 10/12. 9/12 + 10/12 = 19/12.',
    explanationUzCyrl: 'Махражлар 4 ва 6 учун ЭКУК = 12. 3/4 = 9/12 ва 5/6 = 10/12. 9/12 + 10/12 = 19/12.',
    explanationRu: 'Общий знаменатель 12. 9/12 + 10/12 = 19/12 = 1 7/12.',
    explanationEn: 'Common denominator is 12. 9/12 + 10/12 = 19/12 = 1 7/12.',
  },

  {
    id: 'quiz-frac-2',
    category: 'fraction',
    level: 'school',
    questionUzLatn: '2/3 × 9/10 kasrlarni ko‘paytirish natijasini toping:',
    questionUzCyrl: '2/3 × 9/10 касрларни кўпайтириш натижасини топинг:',
    questionRu: 'Вычислите произведение дробей 2/3 × 9/10:',
    questionEn: 'Multiply fractions 2/3 × 9/10:',
    problemInput: '2/3 * 9/10',
    options: [
      { id: 'opt-1', text: '3/5', isCorrect: true },
      { id: 'opt-2', text: '18/30', isCorrect: false },
      { id: 'opt-3', text: '11/13', isCorrect: false },
      { id: 'opt-4', text: '6/15', isCorrect: false },
    ],
    explanationUzLatn: 'Suratlarni va maxrajlarni o‘zaro qisqartiramiz: (2 × 9) / (3 × 10) = 18 / 30 = 3/5.',
    explanationUzCyrl: 'Суратларни ва махражларни ўзаро қисқартирамиз: (2 × 9) / (3 × 10) = 18 / 30 = 3/5.',
    explanationRu: 'Перемножаем числители и знаменатели, сокращаем на 6: 18/30 = 3/5.',
    explanationEn: 'Multiply numerators and denominators, simplify by 6: 18/30 = 3/5.',
  },

  {
    id: 'quiz-frac-3',
    category: 'fraction',
    level: 'lyceum',
    questionUzLatn: '5/8 ÷ 15/16 kasrga bo‘lish amalini bajaring:',
    questionUzCyrl: '5/8 ÷ 15/16 касрга бўлиш амалини бажаринг:',
    questionRu: 'Разделите дробь 5/8 на 15/16:',
    questionEn: 'Divide 5/8 by 15/16:',
    problemInput: '5/8 / (15/16)',
    options: [
      { id: 'opt-1', text: '2/3', isCorrect: true },
      { id: 'opt-2', text: '3/2', isCorrect: false },
      { id: 'opt-3', text: '75/128', isCorrect: false },
      { id: 'opt-4', text: '1/2', isCorrect: false },
    ],
    explanationUzLatn: 'Bo‘lish uchun 5/8 ni 16/15 ga ko‘paytiramiz: (5 × 16) / (8 × 15) = 2/3.',
    explanationUzCyrl: 'Бўлиш учун 5/8 ни 16/15 га кўпайтирамиз: (5 × 16) / (8 × 15) = 2/3.',
    explanationRu: 'Умножаем 5/8 на обратную дробь 16/15: (5*16)/(8*15) = 2/3.',
    explanationEn: 'Multiply 5/8 by reciprocal 16/15: (5*16)/(8*15) = 2/3.',
  },

  // --- AMALLAR TARTIBI (ORDER OF OPERATIONS) ---
  {
    id: 'quiz-order-1',
    category: 'order-of-operations',
    level: 'school',
    questionUzLatn: '24 + (18 - 6) × 3 - 40 ÷ 5 ifodada birinchi bo‘lib qaysi amal bajariladi?',
    questionUzCyrl: '24 + (18 - 6) × 3 - 40 ÷ 5 ифодада биринчи бўлиб қайси амал бажарилади?',
    questionRu: 'Какое действие выполняется первым в 24 + (18 - 6) × 3 - 40 ÷ 5?',
    questionEn: 'Which operation is evaluated first in 24 + (18 - 6) × 3 - 40 ÷ 5?',
    problemInput: '24 + (18 - 6) * 3 - 40 / 5',
    options: [
      { id: 'opt-1', text: 'Qavs ichidagi (18 - 6) ayirish', isCorrect: true },
      { id: 'opt-2', text: '24 + 18 qo‘shish', isCorrect: false },
      { id: 'opt-3', text: '40 ÷ 5 bo‘lish', isCorrect: false },
      { id: 'opt-4', text: '6 × 3 ko‘paytirish', isCorrect: false },
    ],
    explanationUzLatn: 'BODMAS / PEMDAS qoidasiga ko‘ra eng oliy ustuvorlik har doim QAVSLAR (Parentheses)ga tegishli!',
    explanationUzCyrl: 'BODMAS / PEMDAS қоидасига кўра энг олий устуворлик ҳар доим ҚАВСЛАРга тегишли!',
    explanationRu: 'По правилу PEMDAS первое действие всегда выполняется в скобках!',
    explanationEn: 'According to PEMDAS rules, parentheses always have top priority!',
  },

  {
    id: 'quiz-order-2',
    category: 'order-of-operations',
    level: 'school',
    questionUzLatn: '150 - (45 + 15) ÷ 3 × 2 + 18 ifodaning qiymati nechaga teng?',
    questionUzCyrl: '150 - (45 + 15) ÷ 3 × 2 + 18 ифоданинг қиймати нечага тенг?',
    questionRu: 'Чему равно значение 150 - (45 + 15) ÷ 3 × 2 + 18?',
    questionEn: 'Evaluate 150 - (45 + 15) ÷ 3 × 2 + 18:',
    problemInput: '150 - (45 + 15) / 3 * 2 + 18',
    options: [
      { id: 'opt-1', text: '128', isCorrect: true },
      { id: 'opt-2', text: '140', isCorrect: false },
      { id: 'opt-3', text: '110', isCorrect: false },
      { id: 'opt-4', text: '158', isCorrect: false },
    ],
    explanationUzLatn: '1) 45+15=60; 2) 60÷3=20; 3) 20×2=40; 4) 150-40=110; 5) 110+18=128.',
    explanationUzCyrl: '1) 45+15=60; 2) 60÷3=20; 3) 20×2=40; 4) 150-40=110; 5) 110+18=128.',
    explanationRu: '1) 45+15=60; 2) 60/3=20; 3) 20*2=40; 4) 150-40=110; 5) 110+18=128.',
    explanationEn: '1) 45+15=60; 2) 60/3=20; 3) 20*2=40; 4) 150-40=110; 5) 110+18=128.',
  },

  {
    id: 'quiz-order-3',
    category: 'order-of-operations',
    level: 'college',
    questionUzLatn: '8 ÷ 2 × (2 + 2) ifodaning to‘g‘ri matematik yechimi nima?',
    questionUzCyrl: '8 ÷ 2 × (2 + 2) ифоданинг тўғри математик ечими нима?',
    questionRu: 'Каков правильный ответ для 8 ÷ 2 × (2 + 2)?',
    questionEn: 'What is 8 ÷ 2 × (2 + 2)?',
    problemInput: '8 / 2 * (2 + 2)',
    options: [
      { id: 'opt-1', text: '16', isCorrect: true },
      { id: 'opt-2', text: '1', isCorrect: false },
      { id: 'opt-3', text: '8', isCorrect: false },
      { id: 'opt-4', text: '4', isCorrect: false },
    ],
    explanationUzLatn: '1) Qavs ichi: 2+2=4. Qoladi: 8 ÷ 2 × 4. Ko‘paytirish va bo‘lish teng kuchli bo‘lgani uchun chapdan o‘ngga hisoblanadi: 8 ÷ 2 = 4, so‘ng 4 × 4 = 16!',
    explanationUzCyrl: '1) Қавс ичи: 2+2=4. 8 ÷ 2 × 4. Кўпайтириш ва бўлиш чапдан ўнгга: 8 ÷ 2 = 4; 4 × 4 = 16!',
    explanationRu: '1) Скобки: 2+2=4. 8 / 2 * 4 выполняется слева направо: 8/2=4, затем 4*4=16!',
    explanationEn: 'Parentheses: 2+2=4. Then 8 / 2 * 4 left-to-right: 8/2=4, then 4*4=16!',
  },

  // --- TENGLAMALAR (EQUATIONS) ---
  {
    id: 'quiz-eq-1',
    category: 'equation',
    level: 'school',
    questionUzLatn: '3x + 7 = 25 tenglamaning ildizini toping:',
    questionUzCyrl: '3x + 7 = 25 тенгламанинг илдизини топинг:',
    questionRu: 'Решите уравнение 3x + 7 = 25:',
    questionEn: 'Solve 3x + 7 = 25:',
    problemInput: '3x + 7 = 25',
    options: [
      { id: 'opt-1', text: 'x = 6', isCorrect: true },
      { id: 'opt-2', text: 'x = 8', isCorrect: false },
      { id: 'opt-3', text: 'x = 5', isCorrect: false },
      { id: 'opt-4', text: 'x = 9', isCorrect: false },
    ],
    explanationUzLatn: '3x = 25 - 7 => 3x = 18 => x = 18 ÷ 3 => x = 6.',
    explanationUzCyrl: '3x = 25 - 7 => 3x = 18 => x = 18 ÷ 3 => x = 6.',
    explanationRu: '3x = 18, x = 6.',
    explanationEn: '3x = 18, x = 6.',
  },

  {
    id: 'quiz-eq-2',
    category: 'equation',
    level: 'lyceum',
    questionUzLatn: 'x² - 5x + 6 = 0 kvadrat tenglamaning ildizlarini toping:',
    questionUzCyrl: 'x² - 5x + 6 = 0 квадрат тенгламанинг илдизларини топинг:',
    questionRu: 'Найдите корни x² - 5x + 6 = 0:',
    questionEn: 'Find roots of x² - 5x + 6 = 0:',
    problemInput: 'x^2 - 5x + 6 = 0',
    options: [
      { id: 'opt-1', text: 'x₁ = 2, x₂ = 3', isCorrect: true },
      { id: 'opt-2', text: 'x₁ = -2, x₂ = -3', isCorrect: false },
      { id: 'opt-3', text: 'x₁ = 1, x₂ = 6', isCorrect: false },
      { id: 'opt-4', text: 'x₁ = -1, x₂ = 5', isCorrect: false },
    ],
    explanationUzLatn: 'D = (-5)² - 4·1·6 = 25 - 24 = 1. x = (5 ± 1)/2 => x₁ = 3, x₂ = 2.',
    explanationUzCyrl: 'D = 25 - 24 = 1. x = (5 ± 1)/2 => x₁ = 3, x₂ = 2.',
    explanationRu: 'D = 1, корни 2 и 3.',
    explanationEn: 'D = 1, roots are 2 and 3.',
  },

  // --- FIZIKA (PHYSICS) ---
  {
    id: 'quiz-phys-1',
    category: 'physics',
    level: 'school',
    questionUzLatn: 'Massasi 5 kg bo‘lgan jismga 20 N kuch ta‘sir qilsa, uning tezlanishi qanday bo‘ladi?',
    questionUzCyrl: 'Массаси 5 кг бўлган жисмга 20 Н куч таъсир қилса, унинг тезланиши қандай бўлади?',
    questionRu: 'Каково ускорение тела массой 5 кг при силе 20 Н?',
    questionEn: 'What is the acceleration of a 5 kg mass under 20 N force?',
    problemInput: 'm = 5 kg, F = 20 N, a = ?',
    options: [
      { id: 'opt-1', text: '4 m/s²', isCorrect: true },
      { id: 'opt-2', text: '100 m/s²', isCorrect: false },
      { id: 'opt-3', text: '0.25 m/s²', isCorrect: false },
      { id: 'opt-4', text: '15 m/s²', isCorrect: false },
    ],
    explanationUzLatn: 'Nyutonning 2-qonuni: F = m·a => a = F/m = 20 N / 5 kg = 4 m/s².',
    explanationUzCyrl: 'Ньютоннинг 2-қонуни: F = m·a => a = F/m = 20 / 5 = 4 м/с².',
    explanationRu: 'По второму закону Ньютона a = F/m = 20/5 = 4 м/с².',
    explanationEn: 'By Newton\'s second law a = F/m = 20/5 = 4 m/s².',
  },

  {
    id: 'quiz-phys-2',
    category: 'physics',
    level: 'school',
    questionUzLatn: '12 V kuchlanish ostidagi lampochkadan 4 Ω qarshilikda qanday tok oqadi?',
    questionUzCyrl: '12 В кучланиш остидаги лампочкадан 4 Ом қаршиликда қандай ток оқади?',
    questionRu: 'Какой ток течет через лампу 4 Ом при напряжении 12 В?',
    questionEn: 'What current flows through a 4 Ω lamp at 12 V?',
    problemInput: 'U = 12 V, R = 4 ohm, I = ?',
    options: [
      { id: 'opt-1', text: '3 A', isCorrect: true },
      { id: 'opt-2', text: '48 A', isCorrect: false },
      { id: 'opt-3', text: '0.33 A', isCorrect: false },
      { id: 'opt-4', text: '8 A', isCorrect: false },
    ],
    explanationUzLatn: 'Om qonuni: I = U / R = 12 V / 4 Ω = 3 A.',
    explanationUzCyrl: 'Ом қонуни: I = U / R = 12 / 4 = 3 А.',
    explanationRu: 'Закон Ома: I = U/R = 12/4 = 3 А.',
    explanationEn: 'Ohm\'s Law: I = U/R = 12/4 = 3 A.',
  },

  {
    id: 'quiz-phys-3',
    category: 'physics',
    level: 'lyceum',
    questionUzLatn: 'Avtomobil 72 km/h tezlik bilan harakatlanmoqda. Bu tezlik SI sistemasida (m/s) nechaga teng?',
    questionUzCyrl: 'Автомобиль 72 км/ч тезлик билан ҳаракатланмоқда. Бу тезлик СИ системасида (м/с) нечага тенг?',
    questionRu: 'Автомобиль едет со скоростью 72 км/ч. Сколько это в м/с?',
    questionEn: 'A car moves at 72 km/h. What is this in m/s?',
    problemInput: '72 km/h',
    options: [
      { id: 'opt-1', text: '20 m/s', isCorrect: true },
      { id: 'opt-2', text: '25.9 m/s', isCorrect: false },
      { id: 'opt-3', text: '72 m/s', isCorrect: false },
      { id: 'opt-4', text: '15 m/s', isCorrect: false },
    ],
    explanationUzLatn: 'km/h dan m/s ga o‘tish uchun 3.6 ga bo‘lamiz: 72 ÷ 3.6 = 20 m/s.',
    explanationUzCyrl: 'км/ч дан м/с га ўтиш учун 3.6 га бўламиз: 72 ÷ 3.6 = 20 м/с.',
    explanationRu: 'Делим на 3.6: 72 / 3.6 = 20 м/с.',
    explanationEn: 'Divide by 3.6: 72 / 3.6 = 20 m/s.',
  },
];
